### PR TITLE
expt: use migra to perform schema diff

### PR DESCRIPTION
**Pull request by sweatybridge**
## What kind of change does this PR introduce?

experimental feature

## What is the current behavior?

pgadmin diff is verbose and sometimes incorrect

## What is the new behavior?

migra diff is more succinct and mostly correct

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by soedirgo** [comment]
This gives me an error on the first `db commit`:
```
Creating shadow database...
Error: Error creating shadow database: NOTICE:  database "supabase_shadow" does not exist, skipping

exit status 1
```
But subsequent runs seem to work fine

**Comment by sweatybridge** [comment]
@soedirgo nice catch, had to silent notice messages from psql.

**Review by soedirgo — APPROVED** [review]
LGTM!

**Comment by sweatybridge** [comment]
Thanks @pocin for helping us to try this out. One of the reasons for running migra and pgadmin side by side is to enlist some help from users to figure out which one works best for their schema and report any issues here.

> i am personally using the pgadmin gui and it's spot on.

I tested through pgadmin gui as well, using a simple e-commerce db schema. Pasting some generated migration scripts here for you to compare between `migra==3.0.1658662267` and `pgadmin==6.11`.

migra:
```sql
create table "public"."order" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "quantity" smallint not null,
    "complete" boolean not null default false
);

alter table "public"."order" enable row level security;

CREATE UNIQUE INDEX order_pkey ON public."order" USING btree (id);

alter table "public"."order" add constraint "order_pkey" PRIMARY KEY using index "order_pkey";
```

pgadmin
```sql
BEGIN;
-- diff 1 (bad?): migra uses CREATE UNIQUE INDEX which is more concise than raw sequence
-- diff 1 (good?): it's probably a good practice to add IF NOT EXISTS for idempotency
CREATE SEQUENCE IF NOT EXISTS public.order_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

-- diff 2 (good): unlike migra, pgadmin tracks ownership of table
ALTER SEQUENCE public.order_id_seq
    OWNER TO supabase_admin;

-- diff 3 (bad): these role grants are unnecessary due to default privileges
GRANT ALL ON SEQUENCE public.order_id_seq TO anon;

GRANT ALL ON SEQUENCE public.order_id_seq TO authenticated;

GRANT ALL ON SEQUENCE public.order_id_seq TO postgres;

GRANT ALL ON SEQUENCE public.order_id_seq TO service_role;

GRANT ALL ON SEQUENCE public.order_id_seq TO supabase_admin;
CREATE TABLE IF NOT EXISTS public."order"
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    quantity smallint NOT NULL,
    complete boolean NOT NULL DEFAULT false,
    CONSTRAINT order_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."order"
    OWNER to supabase_admin;

ALTER TABLE IF EXISTS public."order"
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public."order" TO anon;

GRANT ALL ON TABLE public."order" TO postgres;

GRANT ALL ON TABLE public."order" TO supabase_admin;

GRANT ALL ON TABLE public."order" TO authenticated;

GRANT ALL ON TABLE public."order" TO service_role;

END;
```

> It even generates the migration script in correct ordering.

I discovered a rather common case where a new table (pet) is added *and* the old table (order) is updated to reference the new table via foreign key constraint (pet_id) in one migration, the generated script isn't executable due to incorrect ordering. See diff 4 below.

migra
```sql
create table "public"."pet" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "name" text not null,
    "tags" text[] not null,
    "meta" json
);


alter table "public"."pet" enable row level security;

alter table "public"."order" add column "pet_id" bigint;

CREATE UNIQUE INDEX pet_pkey ON public.pet USING btree (id);

alter table "public"."pet" add constraint "pet_pkey" PRIMARY KEY using index "pet_pkey";

alter table "public"."order" add constraint "order_pet_id_fkey" FOREIGN KEY (pet_id) REFERENCES pet(id) not valid;

alter table "public"."order" validate constraint "order_pet_id_fkey";
```

pgadmin
```sql
BEGIN;
CREATE SEQUENCE IF NOT EXISTS public.pet_id_seq
    INCREMENT 1
    START 1
    MINVALUE 1
    MAXVALUE 9223372036854775807
    CACHE 1;

ALTER SEQUENCE public.pet_id_seq
    OWNER TO supabase_admin;

GRANT ALL ON SEQUENCE public.pet_id_seq TO anon;

GRANT ALL ON SEQUENCE public.pet_id_seq TO authenticated;

GRANT ALL ON SEQUENCE public.pet_id_seq TO postgres;

GRANT ALL ON SEQUENCE public.pet_id_seq TO service_role;

GRANT ALL ON SEQUENCE public.pet_id_seq TO supabase_admin;
ALTER TABLE IF EXISTS public."order"
    OWNER TO supabase_admin;

REVOKE ALL ON TABLE public."order" FROM anon;
REVOKE ALL ON TABLE public."order" FROM authenticated;
REVOKE ALL ON TABLE public."order" FROM postgres;
REVOKE ALL ON TABLE public."order" FROM service_role;
GRANT ALL ON TABLE public."order" TO anon;

GRANT ALL ON TABLE public."order" TO postgres;

GRANT ALL ON TABLE public."order" TO supabase_admin;

GRANT ALL ON TABLE public."order" TO authenticated;

GRANT ALL ON TABLE public."order" TO service_role;

ALTER TABLE IF EXISTS public."order"
    ADD COLUMN pet_id bigint;
-- diff 4 (very bad): this fk constraint on pet_id must come after pet table creation
ALTER TABLE IF EXISTS public."order"
    ADD CONSTRAINT order_pet_id_fkey FOREIGN KEY (pet_id)
    REFERENCES public.pet (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE TABLE IF NOT EXISTS public.pet
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    name text COLLATE pg_catalog."default" NOT NULL,
    tags text[] COLLATE pg_catalog."default" NOT NULL,
    meta json,
    CONSTRAINT pet_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.pet
    OWNER to supabase_admin;

ALTER TABLE IF EXISTS public.pet
    ENABLE ROW LEVEL SECURITY;

GRANT ALL ON TABLE public.pet TO anon;

GRANT ALL ON TABLE public.pet TO postgres;

GRANT ALL ON TABLE public.pet TO supabase_admin;

GRANT ALL ON TABLE public.pet TO authenticated;

GRANT ALL ON TABLE public.pet TO service_role;

END;
```

> it's said that migra doesnt track view ownership

Yes, I believe this is still the case as migra also doesn't track ownership of table (see diff 2).

In addition, we also found that foreign table relations can crash migra and we haven't found a fix. But overall I feel that neither tool does the job perfectly at its current version (we still need to do more testing to confirm this).

As a general rule of thumb, users with simple schema are probably better off using migra as migrations are 10x faster to generate. When new tables are created with specific ownership, some manual editing is required. But hopefully this is less onerous now that migration scripts are concise and more readable.

Users with more complex postgres entities, like foreign tables, are probably better off sticking with pgAdmin.

**Pull request merged**
