### PR TITLE
feat: provide interactive support for project deletion

### PR DESCRIPTION
**Pull request by S96EA**
## What kind of change does this PR introduce?
- Support delete proejct using interactive mode

## What is the current behavior?

[1694](https://github.com/supabase/cli/issues/1694)

### CODE REVIEW

**Comment by sweatybridge** [comment]
Sorry for the late reply on this. I think it would be nice to eventually converge on an IaaC solution for resource provisioning using a config file. We have an internal RFC for this but in a nutshell, we are considering a custom terraform provider for this specific use case. For eg. in the future it should be possible to declare a supabase project as a terraform resource.

- main.tf
```tf
# Defines an output for displaying the provisioned project ref on console.
output "project_ref" {
  value       = supabase_project.hello_world.ref
  description = "The project ref of the provisioned instance."
}

# The resource declaration instructs TF to call supabase api to provision a project with the following
# set of params. The organization_id refers to the output from the parent provisioning request.
resource "supabase_project" "hello_world" {
  region          = "ap-southeast-1"
  db_password     = var.db_password
  organization_id = supabase_organization.personal.slug
}

# The parent provisioning request for a supabase organization. TF will create this resource only if
# an organization with the same slug doesn't already exist.
resource "supabase_organization" "personal" {
  name = "personal"
}

# Password is a sensitive variable that can be supplied via the CLI.
# Alternatively, you may configure it to load from secrets storage like vault.
variable "db_password" {
  type      = string
  sensitive = true
}
```

- version.tf
```tf
terraform {
  required_providers {
    supabase = {
      source  = "supabase/terraform-provider"
      version = "~> 1.0"
    }
  }
}

provider "supabase" {
  # Personal access token, defaults to the following order:
  # - Environment variable: SUPABASE_ACCESS_TOKEN 
  # - Native credentials store
  # - Token file: ~/.supabase/access-token
  access_token = file("~/.supabase/access-token")
}
```

You can then run `terraform init / plan / apply` to provision the supabase project from these config files.

The benefits of configuring projects this way is flexibility. You can use variables and data sources to control exactly how sensitive fields like passwords are populated.

**Comment by S96EA** [comment]
> Sorry for the late reply on this. I think it would be nice to eventually converge on an IaaC solution for resource provisioning using a config file. We have an internal RFC for this but in a nutshell, we are considering a custom terraform provider for this specific use case. For eg. in the future it should be possible to declare a supabase project as a terraform resource.
> 
> * main.tf
> 
> ```terraform
> # Defines an output for displaying the provisioned project ref on console.
> output "project_ref" {
>   value       = supabase_project.hello_world.ref
>   description = "The project ref of the provisioned instance."
> }
> 
> # The resource declaration instructs TF to call supabase api to provision a project with the following
> # set of params. The organization_id refers to the output from the parent provisioning request.
> resource "supabase_project" "hello_world" {
>   region          = "ap-southeast-1"
>   db_password     = var.db_password
>   organization_id = supabase_organization.personal.slug
> }
> 
> # The parent provisioning request for a supabase organization. TF will create this resource only if
> # an organization with the same slug doesn't already exist.
> resource "supabase_organization" "personal" {
>   name = "personal"
> }
> 
> # Password is a sensitive variable that can be supplied via the CLI.
> # Alternatively, you may configure it to load from secrets storage like vault.
> variable "db_password" {
>   type      = string
>   sensitive = true
> }
> ```
> 
> * version.tf
> 
> ```terraform
> terraform {
>   required_providers {
>     supabase = {
>       source  = "supabase/terraform-provider"
>       version = "~> 1.0"
>     }
>   }
> }
> 
> provider "supabase" {
>   # Personal access token, defaults to the following order:
>   # - Environment variable: SUPABASE_ACCESS_TOKEN 
>   # - Native credentials store
>   # - Token file: ~/.supabase/access-token
>   access_token = file("~/.supabase/access-token")
> }
> ```
> 
> You can then run `terraform init / plan / apply` to provision the supabase project from these config files.
> 
> The benefits of configuring projects this way is flexibility. You can use variables and data sources to control exactly how sensitive fields like passwords are populated.

Thank you. It appears that we need to implement a Terraform plugin. Do we already have a basic version in place, or do we need to start building one from scratch?

**Comment by sweatybridge** [comment]
> Do we already have a basic version in place, or do we need to start building one from scratch?

We have to build one from scratch. But I'm happy to add a basic version if it's helpful to move this forward.

**Comment by S96EA** [comment]
> > Do we already have a basic version in place, or do we need to start building one from scratch?
> 
> We have to build one from scratch. But I'm happy to add a basic version if it's helpful to move this forward.

I would appreciate it if you could add a basic version of this. If there are any updates, please notify me. Thank you.

**Comment by sweatybridge** [comment]
Sounds good. Meanwhile if you are happy to update this PR with just the iterative delete feature, I would be happy to merge it.

**Comment by S96EA** [comment]
> Sounds good. Meanwhile if you are happy to update this PR with just the interactive projects delete feature, I would be happy to merge it.

Completed, thank you.

**Comment by sweatybridge** [comment]
A basic skeleton repo has been created for the terraform provider https://github.com/supabase/terraform-provider-supabase

Currently we have implemented a `supabase_branch` data source and a `supabase_settings` resource. The next thing is probably `supabase_project` resource.

Feel free to familiarise with the code / create issues if you are still happy to contribute.

**Comment by S96EA** [comment]
> A basic skeleton repo has been created for the terraform provider https://github.com/supabase/terraform-provider-supabase
> 
> Currently we have implemented a `supabase_branch` data source and a `supabase_settings` resource. The next thing is probably `supabase_project` resource.
> 
> Feel free to familiarise with the code / create issues if you are still happy to contribute.

Thank you, I'm going to familiarize myself with this project first.

**Review by sweatybridge — APPROVED** [review]

**Pull request merged**
