### PR TITLE
fix: upgrade postgrest to v10.1.1.20221215

### PR DESCRIPTION
**Pull request by steve-chavez**
Fixes a bug on previous pre-release https://github.com/PostgREST/postgrest/issues/2588

### CODE REVIEW

**Review by sweatybridge — APPROVED** [review]

**Comment by steve-chavez** [comment]
@sweatybridge There's a failure on CI, is it related to this PR?

**Comment by soedirgo** [comment]
It looks like it's for a different image though, very odd https://github.com/supabase/cli/actions/runs/3713728867/jobs/6296965402#step:6:324

**Comment by sweatybridge** [comment]
Oh the logs were from a previous image. We need to manually trigger a job to mirror the dependency images. https://github.com/supabase/cli/actions/workflows/mirror.yml

**Comment by sweatybridge** [comment]
I will rerun CI after mirror job succeeds.

**Pull request merged**
