### PR TITLE
update pgmeta to latest version

### PR DESCRIPTION
**Pull request by kartikk-k**
## What kind of change does this PR introduce?

pgmeta update

## What is the new behavior?
[supabase/postgress-meta#483](https://github.com/supabase/postgres-meta/pull/483#issuecomment-1409849142)

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by sweatybridge** [comment]
There's a problem with latest pgmeta image on arm64 that we are fixing. We will come back to this once upstream is fixed. 

The linked issue on composite type is already resolved in v0.60.3. Could you try again on latest cli?

**Comment by kartikk-k** [comment]
Sorry, but I am new to this so I am unclear with comment so, just to confirm are you asking me to make PR once upstream is fixed?

> There's a problem with latest pgmeta image on arm64 that we are fixing. We will come back to this once upstream is fixed.
> 
> The linked issue on composite type is already resolved in v0.60.3. Could you try again on latest cli?

**Comment by sweatybridge** [comment]
I believe the current image 0.60.3 used by cli already contains the fix for composite type. Could you help confirm?

**Comment by kartikk-k** [comment]
ok got it! Let me update you once confirmed.

**Comment by soedirgo** [comment]
I've updated the image to v0.60.7, which seems to fix the arm64 issue. Thanks for the PR!

**Review by soedirgo — APPROVED** [review]

**Pull request merged**
