### PR TITLE
feat: support self hosted urls with db commands

### PR DESCRIPTION
**Pull request by sweatybridge**
## What kind of change does this PR introduce?

feature

closes https://github.com/supabase/cli/issues/753

## What is the new behavior?

support migrations for self-hosted database via `--db-url` flag, including
- [x] `supabase migration list [--db-url]`
- [x] `supabase migration repair [--db-url]`
- [x] `supabase db dump [--db-url]`
- [x] `supabase db push [--db-url]`
- [x] `supabase db remote commit [--db-url]`
- [x] `supabase db diff [--linked | --db-url]`

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Review by soedirgo — APPROVED** [review]

**Comment by ryanalta** [comment]
OMG, catching up on the release notes from a bunch of versions back and major thanks to all for this one.

**Comment by ayush0402** [comment]
@sweatybridge @soedirgo Is there any documentation regarding how to use the same? I might be a bit lost here but I am trying to run push migrations to a self-hosted supabase docker instance which is running locally at `http://localhost:8000`. Can you help me with how can I achieve this?

**Comment by sweatybridge** [comment]
Yes you can find a self-hosted example in our documentation here https://supabase.com/docs/reference/cli/supabase-db-push

**Comment by djbutler** [comment]
Is it expected behavior for "seed.sql" to be applied to remote databases by default? I want a way to specify seed data for local dev only. Is there a preferred way for me to create migrations that are only applied to the local db (supabase db reset), but not my self-hosted remote db (supabase db reset --db-url <url>)?

**Pull request merged**
