### PR TITLE
fix: remove session config from dumped schema

### LINKED ISSUE #507: supabase start error with generated migration without schema of the table
# Bug report

## Describe the bug

`supabase start` can't accept generated migrations in local dev

## To Reproduce
1. init new supabase local project `supabase init`
2. Run `supabase start`
3. use GUI(Supabase studio) and create two tables with foreign key.
4. create a migration using CLI `supabase db diff --use-migra -f test`
5. Run `supabase stop`
6. Run `supabase start`
7. See error
```
Applying migration 20221011193213_test.sql...
Error: ERROR: relation "[YOUR_TABLE_NAME]" does not exist (SQLSTATE 42P01)
```

I noticed that the generated migration doesn't always add a schema to the table name.

## Example generated migration
```
...
alter table "public"."test" add constraint "test_board_id_fkey" FOREIGN KEY (board_id) REFERENCES [!!!missing schema-->]boards(board_id) not valid;
...
```
in this example is missing the schema name in the boards table
if I edit the file and add the schema manually, then the error disappears.
```
...
alter table "public"."test" add constraint "test_board_id_fkey" FOREIGN KEY (board_id) REFERENCES public.boards(board_id) not valid;
...
```

### PR DESCRIPTION
**Pull request by sweatybridge**
## What kind of change does this PR introduce?

Bug fix #507 

## What is the current behavior?

Session configs are persistent per connection. When using pgx, those emitted from `pg_dump` are carried over to subsequent migrations, resulting in unintended side effects.

## What is the new behavior?

- use [local config](https://www.postgresql.org/docs/13/sql-set.html) where possible
- updates migra to latest version

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by soedirgo** [comment]
Does [`RESET`](https://www.postgresql.org/docs/current/sql-reset.html) work better? Have not tested though

**Comment by maxkostow** [comment]
Could this also be similar to #407 ?

**Review by soedirgo — APPROVED** [review]

**Comment by soedirgo** [comment]
@maxkostow might be a different issue I think. In https://github.com/supabase/cli/issues/404 the tables are schema-qualified but it's still failing - in this case the table isn't schema-qualified (`boards` instead of `public.boards`), which failed because of the `SET`s by pg_dump.

**Comment by sweatybridge** [comment]
> Does [RESET ALL](https://www.postgresql.org/docs/current/sql-reset.html) work better? Have not tested though

Changed to `reset all` since it works and is simpler.

**Pull request merged**
