### PR TITLE
fix(typegen): support db-url that require ssl mode

### PR DESCRIPTION
**Pull request by sweatybridge**
## What kind of change does this PR introduce?

Bug fix https://github.com/supabase/postgres-meta/issues/719

## What is the new behavior?

Updates `postgres-meta` to 0.77.2 for ssl support.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by Mrhoho** [comment]
Will this merge cause this error?
```
npx supabase gen types typescript --db-url=postgresql://postgres:password@localhost:5431/postgres > src/types/database.d.ts
Connecting to localhost
v0.77.2: Pulling from supabase/postgres-meta
f546e941f15b: Pull complete 
06495e08993c: Pull complete 
8f7f70c95d2f: Pull complete 
250e515ba9d8: Pull complete 
87c2f57477b2: Pull complete 
a9db845078fd: Pull complete 
7fada51dd304: Pull complete 
8b8519bb20b4: Pull complete 
9cd5da2c1bd1: Pull complete 
742946c4d253: Pull complete 
Digest: sha256:e093e4848a83c1339700ed03e671f3d4f8b1f4c32ea5b9f0d574fe0eeb5bda32
Status: Downloaded newer image for public.ecr.aws/supabase/postgres-meta:v0.77.2
(node:1) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
file:///usr/src/app/dist/server/server.js:57
        throw new Error(schemasError.message);
              ^

Error: The server does not support SSL connections
    at file:///usr/src/app/dist/server/server.js:57:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.11.1
error running container: exit 1
Try rerunning the command with --debug to troubleshoot the error.
```

**Comment by sweatybridge** [comment]
Yes, could you try the beta release?

```
npx supabase@beta gen types ...
```

**Comment by Mrhoho** [comment]
> Yes, could you try the beta release?
> 
> ```
> npx supabase@beta gen types ...
> ```

It seems that the process hangs without any output for a long time

**Comment by Mrhoho** [comment]
image

```
npx supabase@beta gen types typescript --help                  
Need to install the following packages:
supabase@1.147.1
Ok to proceed? (y) y

npx supabase@beta gen types typescript --db-url=postgresql://postgres:password@localhost:5431/postgres > src/types/database.d.ts
Access token not provided. Supply an access token by running supabase login or setting the SUPABASE_ACCESS_TOKEN environment variable.
```

**Comment by sweatybridge** [comment]
I've found the issue and patched it in the beta release. Thanks for reporting it.

```
$ npx supabase@beta gen types typescript --db-url 'postgresql://postgres:postgres@127.0.0.1:54322/postgres'
Need to install the following packages:
  supabase@1.147.3
Ok to proceed? (y) y
Connecting to 127.0.0.1 54322
(node:1) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

```

**Pull request merged**
