### PR TITLE
chore: upgrade Realtime image to v0.22.4

### PR DESCRIPTION
**Pull request by w3b6x9**

### CODE REVIEW

**Comment by soedirgo** [comment]
Does this upgrade include new migrations?

**Comment by w3b6x9** [comment]
@soedirgo it does.

**Comment by w3b6x9** [comment]
which should be taken care of automatically b/c of the Realtime instructions in the README right?

```bash
command: >
      bash -c "./prod/rel/realtime/bin/realtime eval Realtime.Release.migrate
      && ./prod/rel/realtime/bin/realtime start"
```

**Comment by soedirgo** [comment]
It does on `supabase start`, but wouldn't work on `supabase db reset` because we aren't restarting the container. Updating this branch in a bit

**Comment by w3b6x9** [comment]
@soedirgo gotcha, thanks!

**Pull request merged**
