### PR TITLE
feat(auth): support twilio verify in sms config

### PR DESCRIPTION
**Pull request by sweatybridge**
## What kind of change does this PR introduce?

closes https://github.com/supabase/cli/issues/1375

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by djshubs** [comment]
@sweatybridge thanks for working on this, however my issue is still not resolved. 

Here's my config.toml for twilio verify

```toml
[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = true


# Configure one of the supported SMS providers: `twilio`, `messagebird`, `textlocal`, `vonage`.
[auth.sms.twilio_verify]
enabled = true
account_sid = "env(SUPABASE_AUTH_TWILIO_ACCOUNT_SID)"
message_service_sid ="env(SUPABASE_AUTH_TWILIO_MESSAGE_SERVICE_SID)"
# DO NOT commit your Twilio auth token to git. Use environment variable substitution instead:
auth_token = "env(SUPABASE_AUTH_TWILIO_AUTH_TOKEN)"
```

Still getting the same error.

**Comment by sweatybridge** [comment]
Currently we don't support env substitution in all fields. It is being tracked and worked on in a [separate issue](https://github.com/supabase/cli/issues/1325). For the current release, you need to specify the `account_sid` and `message_service_sid` in config.toml directly.

```toml
# Configure one of the supported SMS providers: `twilio`, `messagebird`, `textlocal`, `vonage`.
[auth.sms.twilio_verify]
enabled = true
account_sid = "123"
message_service_sid ="123"
# DO NOT commit your Twilio auth token to git. Use environment variable substitution instead:
auth_token = "env(SUPABASE_AUTH_TWILIO_AUTH_TOKEN)"
```

**Comment by brianwatroba** [comment]
Confirming I can reproduce this issue (with Twilio SMS). Hard coding the values works for me

**Comment by djshubs** [comment]
Same here, I can confirm that hard coding values works.

**Comment by k2xl** [comment]
Confirming that as of Nov 2024 that hardcoding is the trick and that env var substituting don't work for the others (was pulling my hair out)

**Pull request merged**
